### ISSUE TITLE
Problem extracting deps

### ISSUE THREAD

**Issue by Cold-A-Muse** [cltl/SpaCy-to-NAF#3]
When I run:
`NAF = text_to_NAF(text, nlp, dct=datetime.now(), layers={'raw', 'text', 'terms', 'entities', 'deps', 'chunks'})`

​It correctly processes all sections except for the deps section.
For the deps section it only displays `</deps>` (so not even an opening tag)

**Comment by evanmiltenburg** [comment]
It seems there was a typo in the code, which I fixed in 5eec556.
No time to test the code this week, could you try to see whether it works now?

**Comment by Cold-A-Muse** [comment]
Unfortunately now it just slowly clogs my memory until my computer freezes :sweat_smile:

**Comment by evanmiltenburg** [comment]
Progress! 😄 I'll see what I can do.

**Comment by Cold-A-Muse** [comment]
Hi Emile, did you get the chance to have a look at this issue yet?

**Comment by MartenPostma** [comment]
I just committed a version in which it should be fixed.

**Comment by evanmiltenburg** [comment]
Thanks Marten! I've been meaning to fix this, but haven't had the time..

Op vr 20 sep. 2019 15:30 schreef Marten Postma <notifications@github.com>:
